### ISSUE TITLE
reference type (class) implementation of NMoneys?

### ISSUE THREAD

**Issue by Padhraic** [dgg/nmoneys#36]
Are there any plans to release a version of NMoneys implemented as a class and not a struct. 
This would be really useful for using Money in Entity Framework applications. 

Entity Framework does not support structs, only classes as a [complex type](https://msdn.microsoft.com/library/bb738472(v=vs.100).aspx) columns.

**Comment by dgg** [comment]
To be honest, I have never contemplated the idea of `Money` as a reference type.
It really fits the definition of value type: small, inmutable, representing a value and typically "embedded" in other objects (https://msdn.microsoft.com/en-us/library/ms229017(v=vs.110).aspx and https://msdn.microsoft.com/en-us/library/ms229031(v=vs.110).aspx)

I am not a user of EF myself and I had no idea of that arbitrary constraint but it looks EF team should be getting another +1 on that feature.

I will look into what would be needed for having such a surrogate kind of type for storage, similar to what is done when serializing using ServiceStack

**Comment by Padhraic** [comment]
I had a look at what you have done for ServiceStack and EF would work a little differently. 
Probably a class decorated with the [`ComplexType` attribute](https://visualstudiomagazine.com/articles/2014/04/01/making-complex-types-useful.aspx) with `CurrencyCode` and `Amount` [nullable](https://msdn.microsoft.com/en-us/library/1t3y8s4s.aspx) properties. The class its self could not be nullable but it could have `HasValue` and `Value` properties that would allow access to an instance of Money if one can be created from the properties. This way you would not need to implement all the interfaces of a type, or make the reference type act like a type, just wrap the types internal properties as a class.

Something like below might work.

    [ComplexType]
    public class EFMoney
    {
        private void SetAllFields(decimal? amount, CurrencyIsoCode? currency)
        {
            Amount = amount;
            CurrencyCode = currency;
        }
        
        public CurrencyIsoCode? CurrencyCode { get; set; }

        public decimal? Amount { get; set; }

        public bool HasValue => CurrencyCode.HasValue && Amount.HasValue;

        public Money Value
        {
            get
            {
                if (Amount == null) throw new InvalidOperationException();
                if (CurrencyCode == null) throw new InvalidOperationException();
                return new Money(Amount.Value, CurrencyCode.Value  );
            }
        }
    }

We should also override a couple of functions to support extentions to EF like [EntityFramework.Extended](https://www.nuget.org/packages/EntityFramework.Extended/) and [tracker-enabled-dbcontext](https://www.nuget.org/packages/TrackerEnabledDbContext/).

    bool Equals(EFMoney other) //required by to identify if a change has been made to the complex type object.
    bool Equals(object obj)
    int GetHashCode() 
    string ToString() //should also provide parsing from string to EFMoney
    explicit operator EFMoney(DbDataRecord record)//used to cast from the internal class used by EF to represent complex types
    object FormatMoney(AuditPropertyContext auditProperty) // used by EF.Extended to cast complex types

I have an implementation of this I am using in a EF6 Code first application. I could write up a pull request with an example if you like. Have not looked at EF7 yet so don't know how well this will work but I hear [it works in a similar way to code first](http://blogs.msdn.com/b/adonet/archive/2014/10/21/ef7-what-does-code-first-only-really-mean.aspx) so may not require too many changes.

**Comment by dgg** [comment]
I will be having some time this weekend to get something along those lines ready (and learn something about EF in the process! :-p)
