### ISSUE TITLE
GetObjectData in class Money is incorrect

### ISSUE THREAD

**Issue by VelocityDB** [dgg/nmoneys#40]
Currently is

public void GetObjectData(SerializationInfo info, StreamingContext context)
{
  info.AddValue(Serialization.Data.Money.AMOUNT, Amount);
  info.AddValue(Serialization.Data.Money.CURRENCY, CurrencyCode, **typeof(Currency)**);
}

Should be:
public void GetObjectData(SerializationInfo info, StreamingContext context)
{
  info.AddValue(Serialization.Data.Money.AMOUNT, Amount);
  info.AddValue(Serialization.Data.Money.CURRENCY, CurrencyCode, **typeof(CurrencyIsoCode)**);
}

See https://msdn.microsoft.com/en-us/library/akebc4z9(v=vs.110).aspx

https://github.com/dgg/nmoneys/blob/master/src/NMoneys/Money.Serialization.cs

With this fix, Money serializes fine with VelocityDB, see https://velocitydb.com/

**Comment by dgg** [comment]
I'll look into this this evening but it looks you are totally right about it.

**Comment by dgg** [comment]
I have changed the code as suggested and all tests are still passing.
It is a left-over from the very old times in which `Currency` was serialized alongside the amount.

Funny enough, deserialization works even though the type was not correct
