### ISSUE TITLE
DataGrid OrderBy

### ISSUE THREAD

**Issue by ZARk-be** [dgg/nmoneys#43]
Hello

I've just recently adapted my app to use your excellent lib.
One of my fields contain an amount expressed with NMoneys (different currencies on different rows).

I just tryed binding directly to a NMoneys.Money field, but the datagrid would not order. Am i missing something ?

**Comment by dgg** [comment]
Thanks for using the library, glad that it can help.

As for the issue, I am not sure I am going to be able to help with more context (preferably in the shape of code). Are you able to point to a repository, gist or somewhere where I can reproduce the issue?

**Comment by dgg** [comment]
I guess that either you figured out by now or it is not an issue anymore. Closing
