### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by jmaciene** [dgg/nmoneys#44]
Hallo,  i can not use NMoneys in .NET Core project. When is extension provided?

**Comment by dgg** [comment]
Hi, sorry for the late response but I have been on holiday, away from bits and keyboards.

Yes, you are correct, unfortunately nMoneys is not Core friendly yet and I do not have a deadline or milestone for it yet.
I suspect that a bunch of features need to be refactored or even dropped (binary serialization as the first that comes to my mind) and a major project reorganization.
Is it going to be done, but I am not sure on the how to do it or when :cry: 

It is definitely something that I could use some help to do.
Are you interested in giving a hand?
Anyone with experience targeting Core and "Classic" framework libraries?

**Comment by HakanL** [comment]
It shouldn't be too hard to target .NET Standard, and then have the serialization perhaps specific for the full framework (if the support isn't there in Core). But the key is to have the main project target .NET Standard instead.

**Comment by dgg** [comment]
Yeah, now that tooling is released I am on my way to do it.

However, NMoneys uses some development dependencies that also need to be supported. One of them I own and I am currently in the process of porting it.

However I am struggling a bit on the best/easier approach to manage features (such as serialization) that are full-framework only.

One way would be removing them from the main package/binary (making the project netstandard) and adding them to another project package that targets only the full framework.

An other approach (I am investigating this one with `testing.commons`) is having two projects (the existing one targeting full framework and a new netstandard one) and using excluding patterns for the features not available in netstandard. We would be getting two assemblies, with different features, that would be included in the same package.

I am really not sure which way is better (or even feasible), but I will find out soon.
