### ISSUE TITLE
Currnecy and Money can not serialize with binary formatter in .net core 2.0

### ISSUE THREAD

**Issue by bobanco** [dgg/nmoneys#53]
Are there any plans to support SerializableAttribute for .netstandard 2.0?

**Comment by dgg** [comment]
Not at the moment. I thought that binary serialization was not really a "hot" topic anymore.

However...
I do not know how involved would be to target a third framework, but if you really, really need custom binary serialization I can have a quick look.
Can you please send some code exhibiting of the failure, so I can have something that I can start working towards?

Regards
