### ISSUE TITLE
Perhaps int extensions would be nice to have too!

### ISSUE THREAD

**Issue by vgallegob** [dgg/nmoneys#74]
I added int extensions as well, 

```
public static class MoneyExt
{
    public static Money Eur( this int amount ) => new( amount, Currency.Eur );
}
```

It's a bit confusing to put 10m, as it looks like million. I had to look it up.

Perhaps int extensions would be nice to have too!

Anyway, thank you for this library! It's just what I needed. 🥳

**Comment by dgg** [comment]
Maybe @vgallegob you'd like to create a PR?
